greg42/openOfficeMarkup

markupParser/Text/Udoc/DocumentParser.hs

Currently back ticks are not escable and can't get used inside [quote] or [source] without crashing the compiler. This should be fixed by this merge request.

Improve support for back ticks

---

markupParser/Text/Udoc/DocumentParser.hs

The parser crashes if an empty line follows on a block quote. The reason is that the definition of block quote misses to consume the empty lines and therefore expects an end of input afterwards but this exception fails as soon as next non empty line is encountered.

Crash on empty line after block quote

---

markupParser/Text/Udoc/DocumentParser.hs

This patch removes all of the `\` based special character escaping
methods inside the verbatim containers.
Exceptions from this rule are the escaped bold tags `\[b]`, `\[/b]`
and depending on the current container either `\[/source]` or `\[/quote]`.
These exceptions are necessary to ensure that while bold formatting is still
possible inside verbatim containers while the related tags can still be mentioned
inside the container content. The same applies to the expected closing tag.

[Parser] Removes most of the escaping inside the verbatim elements [source] and [quote].

---

.gitignore
OpenOfficeIntegration/Renderer/Renderer.py

This extracts the paragraph generation into a function with a boolean which can be used to express if the new paragraph should be hard enforced or if its only required if the current paragraph is not empty.
This should fix most cases of unwanted empty lines between elements.

[Renderer] Wrapps all paragraph break injecting calls to avoid empt lines if the call happens in an empty paragraph.

---

OpenOfficeIntegration/Renderer/Renderer.py

This is necessary as it can happen that the hook is still present directly after a paragraph break which automatically inserts a space in front of the leading word if its not further wrapped into some kind of container.
Most likely just a workaround for a parser issue in custom meta tags but still worth as it just improves the smart space logic.

[Renderer] Improves the smart space pre render hook to avoid spaces at the start of a paragraph.

---

OpenOfficeIntegration/Renderer/CharacterProperties.py
OpenOfficeIntegration/Renderer/Renderer.py

**Issue**
Skylighting based bold formatting in source code blocks sometimes overflows the block up to the next (inline) source element.
**Potential reason**
The manipulation of character properties like `CharWeight` is done directly through the cursor properties. It seems like this does not always trigger the required update events.
**Fix**
Replace direct property manipulation with calls to `setPropertyValue`.
**Known Issues**
Changing the value of `CharStyleName` will always trigger a full reset of all character properties based on the name related style. This was the same for the old method of property manipulation.

[Renderer] Removes raw character property management with calls to pyuno.

---

OpenOfficeIntegration/Renderer/Renderer.py

This allows to set custom template content area width and height values.
Necessary for child renderers to guess a proper image size, if they use a custom template with content area measurements that do no match the initial values.

[Renderer] Introduce overloadable methods for template with and height.

---

OpenOfficeIntegration/Renderer/Renderer.py
markupParser/Text/Udoc/Document.hs
markupParser/Text/Udoc/DocumentParser.hs

Adds a missing check in the python table helper method  `setColumnWidth()`.
Also includes some missing parser function signatures and short descriptions for these functions.

[Parser|Renderer] Minimal cleanup and some missing function signatures.

---

OpenOfficeIntegration/Renderer/Renderer.py

As a page break is always applied to the current active paragraph, this change is necessary to ensure that the break always appears at the requested position inside the document and not before or after the current active paragraph. This mimics the behavior of libreoffice.

[Renderer] Break paragraph on pagebreak.

---

OpenOfficeIntegration/Renderer/Renderer.py

Refactors the check for `isStartOfParagraph` in `smartSpace` into a custom user definable callback to allow us to add special conditions in which an additional space is (dis)allowed.
**Also introduces three custom checks:**
(1) & (2) ensure that any element rendered after an image or table reference is separated by a space from the previous reference.
(3) Introduces a special case for inline source which is followed by a single `s` to ignore the space and merge the content as we would to it if the word starts with punctuation.  This could be extended to include other cases as well based on the documentation language. I know that this is more a dirty workaround than an actual solution but as long as we do not introduce  methods which change the rendering style based on the current language …

[Renderer] Fix/avoid space between inline source and word ending

---

OpenOfficeIntegration/Renderer/Renderer.py

This should introduce spaces after visible inline meta tags (e.g. footnotes) if the following element is not a simple word but somehow formatted (e.g. inline source or bold text).

[Renderer] Request space if previous item is a visible inline meta tag.

---

markupParser/Text/Udoc/DocumentParser.hs

This allows to indent source code blocks while avoiding a trailing
empty line e.g. to write proper indented source code blocks inside
lists.
Attention: This could break source blocks containing white-space
only languages.

[Parser] Drop  white spaces at source code block end.

---

OpenOfficeIntegration/Renderer/Renderer.py

If the renderer doesn't request a space in case of a leading `(` it shouldn't request one in case of `[`. This might be necessary as references and other things sometimes also appear inside brackets instead of parentheses.
Unsure if this might also is true for `{` and `<`.

[Renderer] Avoid to request a space if the previous word item ends with '['.

---

OpenOfficeIntegration/Renderer/Renderer.py

The previous solution just stored a toc update request in the list
of operations to be done after rendering. As the toc is one of the
first elements in a new document the update request is also one of
first operations inside this list. This is okay as long as none of
the following operations triggers a change for the headings page
numbering.
The new version always triggers a toc update after everything else
is done. If required it should also be possible to split the list
of operations stored in `afterRendering` into `before toc update`
and `after toc update`.

[Renderer] Allow indepedent toc access.

---

markupParser/Text/Udoc/DocumentParser.hs

Change new syntax for ordered lists from `**1.) foo` into `+ foo`

Update new syntax for ordered lists

---

OpenOfficeIntegration/Renderer/Renderer.py

The old rendering hook adds a new space at the beginning of a new
paragraph if the previous one ended with some inline source code.
Reason was a missing check if the next word is at the beginning
of a new paragraph inside the custom `skip_if` lambda inside the
method which handles inline source insertion.

[Renderer] Avoid space after inline source on paragraph end.

---

OpenOfficeIntegration/Renderer/Renderer.py
markupParser/Text/Udoc/Document.hs
markupParser/Text/Udoc/DocumentParser.hs

This allows to format text content with an italic slant:
* Document.hs
- Introduce DocumentItalicFace as new container type including the
required introduction into methods like `showJSON` or
`extractWords`.
* DocumentParser.hs
- Introduce `i` as new container tag name.
* Renderer.py
- Add a handler for `DocumentItalicFace` container. This handler
sets the `CharPosture` attribute of the cursor to italic until
the whole content of the container is renderer.

[Parser|Renderer] Introduce italic support.

---

OpenOfficeIntegration/Renderer/Renderer.py
markupParser/Text/Udoc/Document.hs
markupParser/Text/Udoc/DocumentParser.hs

Add the missing parsing logic for `[inlineImage path = "...", vOffset = ...]`. The renderer already supported it so no further changes on this side.
Multiple Changes here:
- Add `scaling` as new image attribute (Default: `1.0`).
Scaling is applied after size guessing so that any image with a missing scaling factor will not change its size.
- Add `align` as a new image attribute (Default: `center`)
Supported values:
- `center`: Image is centered and no text wrapping occurrences. This should match current behavior
- `left`: Image is left aligned and text wrapping to the right is enabled.
- `right`: Image is right aligned and text wrapping to the left is enabled.
- Wrap image and caption in a frame to ensure that captions are always placed below the image. Side effect: Captions are now …

[Parser|Renderer] Introduce new image tag features

---

markupParser/Text/Udoc/DocumentParser.hs

Fixes rendering issues if a multi line table delimiter contains trailing spaces.

[Parser] Allow trailing spaces in multiline table delimiters.

---

OpenOfficeIntegration/Renderer/Renderer.py
markupParser/Text/Udoc/DocumentParser.hs

This change set enables the use of different kinds of formatted content in headings.
The main purpose of this change set is to avoid accidental line breaks if an inline quote or reference is used inside a heading.  Secondary it will allow to format parts of the heading as bold or italic.

[Parser|Renderer] Allow formatted content in headings.

---

OpenOfficeIntegration/Renderer/Renderer.py

The current definition of `needSpace()` sometimes misses spaces, especially in case of two sequential formatting container (like bold, verbatim or italic). This change set updates the definition of `needSpace()` to ensure that no longer happens.
It also tries to prevent duplicated spaces in case two container get stacked (like bold and italic).

[Renderer] Fix missing spaces between formatted content

---

OpenOfficeIntegration/Renderer/Renderer.py

Ensures to set use the `Standard Text` style for any paragraph even if no initial heading is present.

[Renderer] Always set 'STYLE_STANDARD_TEXT' as initial paragraph style.

---

OpenOfficeIntegration/Renderer/Renderer.py

Injects a superscript formatted comma between sequential footnotes.
This should help to avoid either a missing separation or the missuse
of of the `'` character.
To render successfully this requires the existance of a new style
constant named `STYLE_FOOTNOTE_ANCHOR`.

[Renderer] Separate sequential footnotes.

---

OpenOfficeIntegration/Renderer/Renderer.py

Image and table references which are placed at the end of a bullet point or paragraph appear at the beginning of the next paragraph. The reason current bookmarks used as placeholder are actually empty and therefore get ignored by the paragraph break placement.
This requires all derived parses to introduce `bookmark.setString("")` to delete the content of the placeholder as soon as they inject the actual reference.

[Renderer] Introduce placeholder for bookmarks

---

OpenOfficeIntegration/Renderer/Renderer.py

Delete the internal state storing the last known item during the
initialization of an inline quote to avoid a redundant space if
the first element inside the inline quotation container is not
a simple word but some kind of content creation tag.
This is necessary as the inline quote works like a container and
therefore the renderer still references the last element in front
of the inline quote instead of the container itself.
If the first child element relies on `needSpace()` to determine
if an additional space should be injected it would still base this
decision on the previous element, even if the handler itself already
injected a quotation mark into the text.

[Renderer] Remove redundant space in inline quotes.

---

OpenOfficeIntegration/Renderer/Renderer.py

Sometimes a table cell accidentally ends with an empty paragraph, e.g. if the cell contains an ordered or unordered list. To avoid those lines a new check got integrated which tries to identity trailing empty paragraphs in table cells and removes them.

[Renderer] Remove trailing empty lines in tables.

---

OpenOfficeIntegration/Renderer/Renderer.py

The renderer sometimes stuck if it encounters consecutive images, especially if those span multiple pages and multiple of them potentially fit onto the same page.
It seems like this is mostly a problem related to the anchoring and orientation behavior handling. This has been fixed in that the whole related handling got moved to the surrounding frame instead of the inner image element.

Fix: Rendere Stuck On Image Placement

---

OpenOfficeIntegration/Renderer/Renderer.py

Discovered some issues .. will come back later with an update.
-------------------------------------------------------------------------
As some of the character properties like 'CharStyleName' potentially
influence any of the other properties it isn't enough to just restore
it to its original value (e.g. the default value of 'CharStyleName'
clears the 'CharWeight' back to 100.0).
This was discovered based on example like the following one, which will
remove the bold formatting as soon as the first inline source got closed.
```
[b]{0xf9} {0xf9}[/b]
```
Therefore the new approach allows to restore not only the current
property but also any other one, which is writable and not empty.
For some currently unknown reasons this isn't possible for each property
it was therefore possible to …

[Draft] Allow to restore character properties.

---

OpenOfficeIntegration/Renderer/Renderer.py

Should fix a regression which prevents proper heading formatting, e.g. after inline source elements.
Seems like this regression is related to one of the properties we restore to default but didn't change in the first place. Therefore, LibreOffice starts to assume that there is already a custom text style applied which sometimes prevent the usage of other Fonts.

[Renderer] Don't restore unchanged properties. 

---

OpenOfficeIntegration/Renderer/Renderer.py

Allows to put `s` and `'s` after any kind of inline formatting (source, italic, bold) without an intermediate space.

Allow `s` and `'s` after inline formatting.

---

OpenOfficeIntegration/Renderer/Renderer.py

If an `[imgref]` or `[tblref]` got placed inside a table cell the renderer crashed. This was triggered by a wrong document reference, as the original document refering to the cell got already replaced at the time the post render hook is executed.
... fixes #40

[Renderer] Allows imgref and tblref in tables.

---

markupParser/Text/Udoc/DocumentParser.hs

Previously the parser interpreated everything after a leading `+` as content of the olist item. This resulted in cases where an international phone number got recognized as new olist item.
This should now be fixed.

[Renderer] Enforce at least one space after `+` to start an olist item.

---

OpenOfficeIntegration/Renderer/Renderer.py

Denies to render any strings, which include non-printable characters, as the underlying LibreOffice renderer wouldn't be able to include those properly into the final document.
This is a render based solution, which detects those strings right before they get inserted into the final document. Therefore the error message contains the final string including some context, but  doesn't contain any hints on the filename or location of the broken strings. 
Alternative solution to #45

[Draft][Renderer] Abort if input contains non-printable characters.
